# Generated by Django 4.2.6 on 2023-10-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opera',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
